---
#cockpit
- name: Install cockpit
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cockpit
    state: latest
  when: cockpit
  notify:
    - restart cockpit

# TODO Install cockpit-selinux when selinux has been found
- name: Install cockpit-selinux
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cockpit-selinux
    state: latest
  notify:
    - restart cockpit
  when: selinux_found

#cockpit-docker
- name: Install cockpit-docker
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cockpit-docker
    state: latest
  when: cockpit_docker
  notify:
    - restart cockpit

#cockpit-networkmanager
- name: Install cockpit-networkmanager
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cockpit-networkmanager
    state: latest
  when: cockpit_networkmanager
  notify:
    - restart cockpit

#cockpit-shell
- name: Install cockpit-shell
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cockpit-shell
    state: latest
  when: cockpit_shell
  notify:
    - restart cockpit

#cockpit-storaged
- name: Install cockpit-storaged
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cockpit-storaged
    state: latest
  when: cockpit_storaged
  notify:
    - restart cockpit

#cockpit-doc
- name: Install cockpit-doc
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cockpit-doc
    state: latest
  when: cockpit_doc
  notify:
    - restart cockpit

#cockpit-kubernetes
- name: Install cockpit-kubernetes
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cockpit-kubernetes
    state: latest
  when: cockpit_kubernetes
  notify:
    - restart cockpit

#cockpit-ostree
- name: Install cockpit-ostree
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cockpit-ostree
    state: latest
  when: cockpit_ostree
  notify:
    - restart cockpit

#cockpit-pcp
- name: Install cockpit-pcp
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cockpit-pcp
    state: latest
  when: cockpit_pcp
  notify:
    - restart cockpit

#cockpit-selinux
- name: Install cockpit-selinux
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cockpit-selinux
    state: latest
  when: cockpit_selinux
  notify:
    - restart cockpit

#cockpit-sosreport
- name: Install cockpit-sosreport
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cockpit-sosreport
    state: latest
  when: cockpit_sosreport
  notify:
    - restart cockpit

#cockpit-subscriptions
- name: Install cockpit-subscriptions
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: cockpit-subscriptions
    state: latest
  when: cockpit_subscriptions
  notify:
    - restart cockpit
