---
- include: repo-debian.yml
  when: cockpit and ansible_distribution == 'Debian'

- include: repo-ubuntu.yml
  when: cockpit and ansible_distribution == 'Ubuntu'

- include: install.yml
  when: cockpit
